services:
  pgdatabase:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "./trends_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

    
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - "./data_pgadmin:/var/lib/pgadmin"
    depends_on:
      - pgdatabase
    ports:
      - "8080:80"
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    container_name: trend-api
    environment:
     - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./shared:/app/shared
    depends_on:
      pgdatabase:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped

  ingestion:
    build:
      context: ./services/ingestion
    container_name: trend-ingestion
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PYTHONUNBUFFERED=1
    depends_on:
      pgdatabase:
        condition: service_healthy
    volumes:
      - ./shared:/app/shared
    restart: unless-stopped

  frontend:
    build: 
      context: ./services/frontend
    container_name: trend-frontend
    depends_on:
      pgdatabase:
        condition: service_healthy
    volumes:
      - ./services/frontend:/app
    ports:
      - 3000:3000
