services:
  pgdatabase:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "./trends_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    restart: unless-stopped

    
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - "./data_pgadmin:/var/lib/pgadmin"
    ports:
      - "8080:80"
    restart: unless-stopped

  app:
    build: .
    container_name: trend-api
    environment:
     - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - pgdatabase
    ports:
      - "5000:5000"
    restart: unless-stopped

  ingestion:
    build:
      context: ./services/ingestion
    container_name: trend-ingestion
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PYTHONUNBUFFERED=1
    depends_on:
      - pgdatabase
    volumes:
      - ./:/app
    restart: unless-stopped

  dashboard:
